2017-08-29 00:26:18,767:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:26:18,789:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='execute uspaddFactura4 339,'2018-01-01','car339''
2017-08-29 00:26:58,311:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:27:33,441:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='execute uspaddFactura4 339,'2018-01-01','car339''
2017-08-29 00:27:40,760:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:27:40,785:DEBUG:Error adding record , exception message local variable 'unique_id' referenced before assignment , sql ='execute uspaddFactura4 339,'2018-01-01','car339''
2017-08-29 00:28:21,151:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:30:21,846:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:30:21,872:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'execute uspaddFactura4 339,'2018-01-01','car339';select SCOPE_IDENTITY()'
2017-08-29 00:30:34,148:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:35:23,946:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:35:40,441:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'execute uspaddFactura4 340,'2018-01-01','car340';select SCOPE_IDENTITY()'
2017-08-29 00:35:56,639:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:36:18,732:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:59:29,620:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:02:30,546:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:02:46,976:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:12:03,029:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:37:01,849:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:37:01,870:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:38:54,610:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:38:54,633:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:39:45,863:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:39:45,883:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:40:14,494:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:41:27,749:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:44:40,927:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:45:12,664:DEBUG:Error adding record , exception message (8114, 'Error converting data type varchar to int.DB-Lib error message 8114, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:49:47,134:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:50:07,444:DEBUG:Error adding record , exception message 'datetime.date' object has no attribute 'factura_fecha' , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:50:37,080:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:50:50,674:DEBUG:Error adding record , exception message (8114, 'Error converting data type varchar to int.DB-Lib error message 8114, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:59:44,246:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:00:07,904:DEBUG:Error adding record , exception message (8114, 'Error converting data type varchar to int.DB-Lib error message 8114, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 02:23:15,097:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:23:15,115:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 02:25:20,742:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:26:05,225:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 02:28:16,167:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:28:16,182:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 02:29:27,539:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:29:27,555:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 04:07:47,121:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:07:47,140:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 04:09:40,438:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:09:40,458:DEBUG:Error adding record , exception message (8144, 'Procedure or function uspaddFactura4 has too many arguments specified.DB-Lib error message 8144, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 04:10:21,719:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:13:35,569:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:15:16,014:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:15:23,505:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'execute uspaddFactura4 361,'car361''
2017-08-29 04:15:44,639:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 05:02:42,252:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 05:02:42,273:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'EXEC uspaddFactura4 362,'car362''
2017-08-29 05:02:56,812:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-09-09 16:39:12,771:DEBUG:Error adding record , exception message 'MainTableModel' object has no attribute 'factura_id' , sql ='None'
2017-09-10 15:10:07,034:DEBUG:Error adding record , exception message Cursor instance has no attribute 'lastrowid' , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 15:12:37,921:DEBUG:Error adding record , exception message local variable 'lastrowid' referenced before assignment , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 15:15:45,275:DEBUG:Error adding record , exception message local variable 'lastrowid' referenced before assignment , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 15:20:34,138:DEBUG:Error reading record with key 59 , exception message (u'42S02', u"[42S02] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'tb_factura4'."), sql = 'select factura_id,factura_fecha,xmin,autoi,tb_factura_item_id from tb_factura4 where autoi = 59'
2017-09-10 15:24:28,448:DEBUG:Error reading record with key 61 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'pk_key'."), sql = 'select pk_key,anytext where pk_key = 61'
2017-09-10 15:25:15,845:DEBUG:Error reading record with key 63 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'pk_key'."), sql = 'select pk_key,anytext where pk_key = 63'
2017-09-10 15:27:00,145:DEBUG:Error reading record with key 65 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'pk_key'."), sql = 'select pk_key,anytext from tb_maintable where pk_key = 65'
2017-09-10 15:28:00,424:DEBUG:Too many records -1 results for read a record with query - select pk_id,anytext from tb_maintable where pk_id = 67
2017-09-10 15:42:56,830:DEBUG:Too many records -1 results for read a record with query - select pk_id,anytext from tb_maintable where pk_id = 69
2017-09-10 15:43:37,336:DEBUG:Too many records -1 results for read a record with query - select pk_id,anytext from tb_maintable where pk_id = 71
2017-09-10 15:44:12,258:DEBUG:Error reading record with key 73 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 73'
2017-09-10 15:54:45,930:DEBUG:Error reading record with key 75 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 75'
2017-09-10 16:29:50,761:DEBUG:Error reading record with key 77 , exception message 'list' object has no attribute 'encode', sql = 'select pk_id,anytext from tb_maintable where pk_id = 77'
2017-09-10 16:30:44,662:DEBUG:Error reading record with key 79 , exception message 'list' object has no attribute 'encode', sql = 'select pk_id,anytext from tb_maintable where pk_id = 79'
2017-09-10 16:30:49,506:DEBUG:Error reading record with key 81 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 81'
2017-09-10 16:42:12,548:DEBUG:Error reading record with key 83 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 83'
2017-09-10 16:42:26,432:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer,host=192.168.0.9,port=None,database=db_pytest,user=sa,password=melivane 
2017-09-10 16:44:07,502:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer,host=192.168.0.9,port=None,database=db_pytest,user=sa,password=melivane 
2017-09-10 16:45:01,446:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer,host=192.168.0.9,port=None,database=db_pytest,user=sa,password=melivane 
2017-09-10 16:48:14,950:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer,host=192.168.0.9,port=None,database=db_pytest,user=sa,password=melivane 
2017-09-10 16:51:56,104:DEBUG:Error reading record with key 99 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 99'
2017-09-10 17:21:02,159:DEBUG:Too many records -1 results for read a record with query - select pk_id,anytext from tb_maintable where pk_id = 101
2017-09-10 17:22:43,373:DEBUG:Error reading record with key 103 , exception message 'Row' object has no attribute 'column_name', sql = 'select pk_id,anytext from tb_maintable where pk_id = 103'
2017-09-10 17:24:06,137:DEBUG:Error reading record with key 105 , exception message 'Row' object has no attribute 'column_name', sql = 'select pk_id,anytext from tb_maintable where pk_id = 105'
2017-09-10 17:24:10,146:DEBUG:Error reading record with key 107 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 107'
2017-09-10 17:31:50,627:DEBUG:Error reading record with key 109 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 109'
2017-09-10 17:31:54,060:DEBUG:Error reading record with key 111 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 111'
2017-09-10 17:32:32,237:DEBUG:Error reading record with key 113 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 113'
2017-09-10 17:52:23,210:DEBUG:Error reading record with key 115 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 115'
2017-09-10 17:52:48,623:DEBUG:Error reading record with key 117 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 117'
2017-09-10 20:08:39,966:DEBUG:Error reading record with key 119 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 119'
2017-09-10 20:09:23,761:DEBUG:Error reading record with key 121 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 121'
2017-09-10 20:10:06,318:DEBUG:Error reading record with key 123 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 123'
2017-09-10 20:13:01,792:DEBUG:Error reading record with key 125 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 125'
2017-09-10 20:13:11,345:DEBUG:Error reading record with key 127 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 127'
2017-09-10 20:38:55,274:DEBUG:Error reading record with key 129 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 129'
2017-09-10 20:49:10,516:DEBUG:Error reading record with key 131 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 131'
2017-09-10 20:49:56,651:DEBUG:Error reading record with key 133 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 133'
2017-09-10 21:03:43,121:DEBUG:Error reading record with key 139 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 139'
2017-09-10 21:05:45,261:DEBUG:Error reading record with key 149 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 149'
2017-09-10 21:16:53,089:DEBUG:Error reading record with key 153 , exception message 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 153'
2017-09-10 21:17:03,408:DEBUG:Error reading record with key 155 , exception message 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 155'
2017-09-10 21:17:46,791:DEBUG:Error reading record with key 157 , exception message 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 157'
2017-09-10 21:20:06,482:DEBUG:Error reading record with key 159 , exception message 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 159'
2017-09-10 21:28:53,805:DEBUG:Error reading record with key 161 , exception message 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 161'
2017-09-10 21:29:00,507:DEBUG:Error reading record with key 163 , exception message 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 163'
2017-09-10 21:57:33,073:DEBUG:Error reading record with key 165 , exception message 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 165'
2017-09-10 22:01:07,302:DEBUG:Error reading record with key 167 , exception message 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 167'
2017-09-10 22:01:24,140:DEBUG:Error reading record with key 169 , exception message 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 169'
2017-09-10 22:01:55,612:DEBUG:Error reading record with key 171 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 171'
2017-09-10 22:02:41,442:DEBUG:Error reading record with key 173 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 173'
2017-09-10 22:07:41,230:DEBUG:Error reading record with key 181 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 181'
2017-09-10 22:08:31,772:DEBUG:Error reading record with key 183 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 183'
2017-09-10 22:09:35,378:DEBUG:Error reading record with key 185 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 185'
2017-09-10 22:10:05,732:DEBUG:Error reading record with key 187 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 187'
2017-09-10 22:11:28,217:DEBUG:Error reading record with key 189 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 189'
2017-09-10 22:11:44,536:DEBUG:Error reading record with key 191 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 191'
2017-09-10 22:12:04,513:DEBUG:Error reading record with key 193 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 193'
2017-09-10 22:12:17,663:DEBUG:Error reading record with key 195 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 195'
2017-09-10 22:12:49,573:DEBUG:Error reading record with key 197 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 197'
2017-09-10 22:13:46,083:DEBUG:Error reading record with key 199 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 199'
2017-09-10 22:14:09,125:DEBUG:Error reading record with key 201 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 201'
2017-09-10 22:14:23,789:DEBUG:Error reading record with key 203 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 203'
2017-09-10 22:14:56,154:DEBUG:Error reading record with key 205 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 205'
2017-09-10 22:17:41,375:DEBUG:Error reading record with key 207 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 207'
2017-09-10 22:17:46,830:DEBUG:Error reading record with key 209 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 209'
2017-09-10 22:55:37,906:DEBUG:Error reading record with key 211 , exception message local variable 'cursor' referenced before assignment, sql = 'None'
2017-09-10 22:56:20,467:DEBUG:Error reading record with key 213 , exception message Cursor instance has no attribute 'cursor', sql = 'select pk_id,anytext from tb_maintable where pk_id = 213'
2017-09-10 22:56:27,880:DEBUG:Error reading record with key 215 , exception message Cursor instance has no attribute 'cursor', sql = 'select pk_id,anytext from tb_maintable where pk_id = 215'
2017-09-10 22:57:07,797:DEBUG:Error reading record with key 217 , exception message Cursor instance has no attribute 'cursor', sql = 'select pk_id,anytext from tb_maintable where pk_id = 217'
2017-09-10 22:57:54,603:DEBUG:Error reading record with key 219 , exception message Cursor instance has no attribute 'cursor', sql = 'select pk_id,anytext from tb_maintable where pk_id = 219'
2017-09-10 22:58:38,710:DEBUG:Error reading record with key 221 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 221'
2017-09-10 22:58:38,710:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 22:58:57,189:DEBUG:Error reading record with key 223 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 223'
2017-09-10 22:58:57,189:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 22:59:08,457:DEBUG:Error reading record with key 225 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 225'
2017-09-10 22:59:08,458:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 23:00:11,187:DEBUG:Error reading record with key 227 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 227'
2017-09-10 23:00:11,187:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 23:00:14,556:DEBUG:Error reading record with key 229 , exception message global name 'dursor' is not defined, sql = 'select pk_id,anytext from tb_maintable where pk_id = 229'
2017-09-10 23:00:14,556:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 23:00:32,001:DEBUG:Error reading record with key 231 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 231'
2017-09-10 23:00:32,001:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 23:04:04,241:DEBUG:Error reading record with key 235 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 235'
2017-09-10 23:04:04,242:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-10 23:21:12,331:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer;CHARSET=LATIN-1,host=192.168.0.9,port=1433,database=db_pytest,user=sa,password=melivane 
2017-09-11 00:17:40,167:DEBUG:Error reading record with key 237 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 237'
2017-09-11 00:17:40,168:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:29:56,371:DEBUG:Error reading record with key 239 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 239'
2017-09-11 00:29:56,371:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:30:41,400:DEBUG:Error reading record with key 241 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 241'
2017-09-11 00:30:41,400:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:31:38,274:DEBUG:Error reading record with key 243 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 243'
2017-09-11 00:31:38,275:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:33:22,000:DEBUG:Error reading record with key 245 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 245'
2017-09-11 00:33:22,000:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:33:33,599:DEBUG:Error reading record with key 247 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 247'
2017-09-11 00:33:33,599:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:33:56,165:DEBUG:Error reading record with key 249 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 249'
2017-09-11 00:33:56,165:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:34:49,201:DEBUG:Error reading record with key 251 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 251'
2017-09-11 00:34:49,201:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:35:08,706:DEBUG:Error reading record with key 253 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 253'
2017-09-11 00:35:08,706:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:35:18,642:DEBUG:Error reading record with key 255 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 255'
2017-09-11 00:35:18,642:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:35:48,691:DEBUG:Error reading record with key 257 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 257'
2017-09-11 00:35:48,691:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:37:44,990:DEBUG:Error reading record with key 259 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 259'
2017-09-11 00:37:44,990:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:38:29,361:DEBUG:Error reading record with key 261 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 261'
2017-09-11 00:38:29,361:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:38:58,641:DEBUG:Error reading record with key 263 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 263'
2017-09-11 00:38:58,641:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:39:17,540:DEBUG:Error reading record with key 265 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 265'
2017-09-11 00:39:17,541:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:40:19,668:DEBUG:Error reading record with key 267 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 267'
2017-09-11 00:40:19,669:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:40:23,128:DEBUG:Error reading record with key 269 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 269'
2017-09-11 00:40:23,128:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:40:49,349:DEBUG:Error reading record with key 271 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 271'
2017-09-11 00:40:49,349:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:41:04,928:DEBUG:Error reading record with key 273 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 273'
2017-09-11 00:41:04,928:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:41:28,896:DEBUG:Error reading record with key 275 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 275'
2017-09-11 00:41:28,896:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:41:35,614:DEBUG:Error reading record with key 277 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 277'
2017-09-11 00:41:35,614:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:41:48,374:DEBUG:Error reading record with key 279 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 279'
2017-09-11 00:41:48,374:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:46:30,258:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer;CHARSET=LATIN-1,host=192.168.0.9,port=1433,database=db_pytest,user=sa,password=melivane 
2017-09-11 00:47:22,257:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer,host=192.168.0.9,port=1433,database=db_pytest,user=sa,password=melivane 
2017-09-11 00:52:00,050:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer,host=192.168.0.9,port=1433,database=db_pytest,user=sa,password=melivane 
2017-09-11 00:52:49,472:DEBUG:Error reading record with key 281 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 281'
2017-09-11 00:52:49,473:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:57:29,179:DEBUG:Error reading record with key 283 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 283'
2017-09-11 00:57:29,179:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 00:58:13,220:DEBUG:Error reading record with key 285 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 285'
2017-09-11 00:58:13,220:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 01:01:40,347:DEBUG:Error reading record with key 287 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 287'
2017-09-11 01:01:40,347:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 01:01:55,471:DEBUG:Error reading record with key 289 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 289'
2017-09-11 01:01:55,471:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 01:02:42,372:DEBUG:Error reading record with key 291 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 291'
2017-09-11 01:02:42,372:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 01:05:44,107:DEBUG:Error reading record with key 293 , exception message 'NoneType' object has no attribute 'description', sql = 'select pk_id,anytext from tb_maintable where pk_id = 293'
2017-09-11 01:06:52,599:DEBUG:Error reading record with key 295 , exception message 'NoneType' object has no attribute 'description', sql = 'select pk_id,anytext from tb_maintable where pk_id = 295'
2017-09-11 01:09:10,801:DEBUG:Error reading record with key 297 , exception message 'NoneType' object has no attribute 'description', sql = 'select pk_id,anytext from tb_maintable where pk_id = 297'
2017-09-11 01:09:16,179:DEBUG:Error reading record with key 299 , exception message Cursor is closed., sql = 'select pk_id,anytext from tb_maintable where pk_id = 299'
2017-09-11 01:09:58,688:DEBUG:Error reading record with key 301 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 301'
2017-09-11 01:09:58,688:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 01:10:06,011:DEBUG:Error reading record with key 303 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 303'
2017-09-11 01:10:06,011:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 01:12:24,215:DEBUG:Error reading record with key 305 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 305'
2017-09-11 01:12:24,215:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 01:13:09,906:DEBUG:Error reading record with key 307 , exception message ('', 'SQL_INVALID_HANDLE'), sql = 'select pk_id,anytext from tb_maintable where pk_id = 307'
2017-09-11 01:13:09,906:DEBUG:Error adding record , exception message ('', 'SQL_INVALID_HANDLE') , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-11 01:13:55,335:DEBUG:Error reading record with key 309 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 309'
2017-09-11 01:17:12,162:DEBUG:Error reading record with key 311 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 311'
2017-09-11 01:21:20,227:DEBUG:Error reading record with key 325 , exception message 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 325'
2017-09-11 01:21:48,826:DEBUG:Error reading record with key 327 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 327'
2017-09-11 01:27:13,429:DEBUG:Error reading record with key 347 , exception message 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 347'
2017-09-11 01:38:48,187:DEBUG:Error reading record with key 355 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 355'
2017-09-11 01:49:24,386:DEBUG:Error reading record with key 377 , exception message 'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256), sql = 'select pk_id,anytext from tb_maintable where pk_id = 377'
2017-09-11 05:08:08,678:DEBUG:Error starting transaction adding a record , exception message Cant load driver with parameters dsn=MSSQLServer,host=192.168.0.9,port=1433,database=db_pytest,user=sa,password=melivane 
2017-09-11 05:12:32,435:DEBUG:Error reading record with key 417 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 417'
2017-09-11 05:14:27,266:DEBUG:Error reading record with key 419 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 419'
2017-09-11 05:15:02,041:DEBUG:Error reading record with key 421 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 421'
2017-09-11 05:17:50,906:DEBUG:Error reading record with key 423 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 423'
2017-09-11 05:19:10,835:DEBUG:Error reading record with key 425 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 425'
2017-09-11 05:25:05,518:DEBUG:Error reading record with key 427 , exception message 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128), sql = 'select pk_id,anytext from tb_maintable where pk_id = 427'
2017-09-11 05:40:51,555:DEBUG:Error reading record with key 437 , exception message global name 'pyodbc' is not defined, sql = 'select pk_id,anytext from tb_maintable where pk_id = 437'
2017-09-11 05:42:41,400:DEBUG:Error reading record with key 439 , exception message global name 'pyodbc' is not defined, sql = 'select pk_id,anytext from tb_maintable where pk_id = 439'
2017-09-14 01:02:34,171:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-14 01:02:34,180:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-14 01:03:24,731:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-14 01:05:33,162:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-14 01:26:12,795:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-14 01:27:08,578:DEBUG:Error reading record with key None , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-14 01:27:32,422:DEBUG:Error reading record with key None , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-14 02:25:55,723:DEBUG:Error reading record with key None , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-14 15:15:49,071:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test_dsp';'
2017-09-14 15:19:34,452:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test_dsp';'
2017-09-14 15:22:24,920:DEBUG:Error adding record , exception message global name 'key' is not defined , sql ='None'
2017-09-14 15:23:16,335:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC withSelectspInsertTest 'test_dsp';'
2017-09-14 15:23:39,402:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 15:23:49,370:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 15:25:10,006:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 15:36:04,256:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 15:36:58,874:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 15:41:38,115:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 15:41:54,517:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 15:42:24,140:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 15:44:43,667:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 16:00:11,659:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 16:09:58,288:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 16:10:56,452:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 16:12:46,591:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 16:14:34,370:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:01:13,826:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:07:51,376:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:08:52,598:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:12:24,862:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:12:36,768:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:14:11,573:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:15:02,046:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:15:32,912:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-14 17:17:17,641:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='set nocount on;EXEC withSelectspInsertTest 'test_spid';'
2017-09-15 02:41:43,545:DEBUG:Error reading record with key foo , exception message (207, "Invalid column name 'foo'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = foo'
2017-09-15 02:42:13,163:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;declare @id int;declare @pp varchar(10);EXEC withOutParamInsertTest 'test_dsp',@id output,@pp output;select @pp;select @id;'
2017-09-15 02:42:39,691:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-15 02:43:05,109:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-15 02:44:15,761:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-15 02:45:41,401:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test_dsp';'
2017-09-15 02:53:05,682:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test_dsp';'
2017-09-15 02:53:25,096:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test_dsp';'
2017-09-15 02:53:57,114:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test_dsp';'
2017-09-15 02:54:05,744:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test_dsp';'
2017-09-15 03:17:17,271:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;declare @id int;declare @pp varchar(10);EXEC withOutParamInsertTest 'test_dsp',@id output,@pp output;select @pp;select @id;'
2017-09-15 03:17:30,762:DEBUG:Error reading record with key None , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-15 05:09:39,927:DEBUG:Error adding record , exception message 'MainTableModel' object has no attribute 'fktest' , sql ='None'
2017-09-15 05:10:08,204:DEBUG:Error adding record , exception message 'MainTableModel' object has no attribute 'fktest' , sql ='None'
2017-09-15 05:11:41,211:DEBUG:Error adding record , exception message 'MainTableModel' object has no attribute 'fktest' , sql ='None'
2017-09-15 05:11:48,427:DEBUG:Error adding record , exception message 'MainTableModel' object has no attribute 'fktest' , sql ='None'
2017-09-15 05:12:04,783:DEBUG:Error adding record , exception message 'MainTableModel' object has no attribute 'fktest' , sql ='None'
2017-09-15 05:25:56,812:DEBUG:Error adding record , exception message (u'23000', u'[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The INSERT statement conflicted with the FOREIGN KEY constraint "FK_tb_maintable_fk_tb_testfk". The conflict occurred in database "db_pytest", table "dbo.tb_testfk", column \'fktest\'.') , sql ='insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 05:26:12,430:DEBUG:Error adding record , exception message (u'23000', u'[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The INSERT statement conflicted with the FOREIGN KEY constraint "FK_tb_maintable_fk_tb_testfk". The conflict occurred in database "db_pytest", table "dbo.tb_testfk", column \'fktest\'.') , sql ='insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 05:28:31,973:DEBUG:Error adding record , exception message (u'23000', u'[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The INSERT statement conflicted with the FOREIGN KEY constraint "FK_tb_maintable_fk_tb_testfk". The conflict occurred in database "db_pytest", table "dbo.tb_testfk", column \'fktest\'.') , sql ='insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 05:33:09,431:DEBUG:Error adding record , exception message (u'23000', u'[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The INSERT statement conflicted with the FOREIGN KEY constraint "FK_tb_maintable_fk_tb_testfk". The conflict occurred in database "db_pytest", table "dbo.tb_testfk", column \'fktest\'.') , sql ='insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 05:33:26,205:DEBUG:Error adding record , exception message (u'23000', u'[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The INSERT statement conflicted with the FOREIGN KEY constraint "FK_tb_maintable_fk_tb_testfk". The conflict occurred in database "db_pytest", table "dbo.tb_testfk", column \'fktest\'.') , sql ='insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 05:33:52,156:DEBUG:Error adding record , exception message (u'23000', u'[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]The INSERT statement conflicted with the FOREIGN KEY constraint "FK_tb_maintable_fk_tb_testfk". The conflict occurred in database "db_pytest", table "dbo.tb_testfk", column \'fktest\'.') , sql ='insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 05:33:54,795:DEBUG:Error adding record , foreign key error,sql = 'insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 05:36:36,760:DEBUG:Error adding record , foreign key error,sql = 'insert into tb_maintable_fk(anytext,fktest) values ('test',1)'
2017-09-15 05:38:23,922:DEBUG:Error adding record , foreign key error,sql = 'insert into tb_maintable_fk(anytext,fktest) values ('test',1)'
2017-09-15 05:42:36,048:DEBUG:Error adding record , foreign key error,sql = 'insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 15:25:30,629:DEBUG:Error adding record , exception message global name 'type_test' is not defined , sql ='None'
2017-09-15 15:26:20,097:DEBUG:Error adding record , exception message 'MssqlDaoTest' object has no attribute 'type_test' , sql ='None'
2017-09-15 15:26:29,544:DEBUG:Error adding record , exception message 'MssqlDaoTest' object has no attribute 'type_test' , sql ='None'
2017-09-15 15:27:50,386:DEBUG:Error adding record , foreign key error,sql = 'insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 16:11:55,793:DEBUG:Error adding record , foreign key error,sql = 'insert into tb_maintable_fk(anytext,fktest) values ('test',2)'
2017-09-15 16:12:45,400:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test';'
2017-09-15 16:14:37,467:DEBUG:Error adding record , exception message Unsupported , cant get LAST ID for DIRECT_SP... , sql ='set nocount on;EXEC directspInsertTest 'test';'
2017-09-15 22:48:52,462:DEBUG:Error adding record , exception message (2627, "Violation of UNIQUE KEY constraint 'IX_tb_maintable_fk'. Cannot insert duplicate key in object 'dbo.tb_maintable_fk'. The duplicate key value is (IsDuplicate).DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\n") , sql ='insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'IsDuplicate')'
2017-09-15 22:51:29,222:DEBUG:Error adding record , exception message (2627, "Violation of UNIQUE KEY constraint 'IX_tb_maintable_fk'. Cannot insert duplicate key in object 'dbo.tb_maintable_fk'. The duplicate key value is (IsDuplicate2).DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\n") , sql ='insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'IsDuplicate2')'
2017-09-15 22:53:34,410:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'IsDuplicate2')'
2017-09-15 22:53:35,880:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'IsDuplicate2')'
2017-09-15 22:54:02,427:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'IsDuplicate4')'
2017-09-15 23:28:27,174:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'IsDuplicate5')'
2017-09-15 23:34:53,290:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'IsDuplicate5')'
2017-09-15 23:35:44,938:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'El segundo')'
2017-09-15 23:38:23,922:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'IsDuplicate5')'
2017-09-15 23:39:47,369:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'El segundo')'
2017-09-16 01:14:19,087:DEBUG:Error adding record , exception message (u'23000', u"[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'IX_tb_maintable_fk'. Cannot insert duplicate key in object 'dbo.tb_maintable_fk'. The duplicate key value is (El segundo 8).") , sql ='insert into tb_maintable_fk(anytext,fktest,nondup) values ('test',1,'El segundo 8')'
2017-09-18 00:33:59,480:DEBUG:Error reading record with key None , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-18 00:41:16,127:DEBUG:Error adding record , exception message Cursor instance has no attribute 'lastrowid' , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-18 00:42:09,845:DEBUG:Error adding record , exception message get_UID() takes exactly 2 arguments (3 given) , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-18 00:44:44,622:DEBUG:Error adding record , exception message 'DAODelegateTest' object has no attribute 'execute' , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-18 00:58:19,085:DEBUG:Error adding record , exception message get_UID() takes exactly 1 argument (2 given) , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-18 01:00:55,454:DEBUG:Error adding record , exception message get_UID() takes exactly 1 argument (2 given) , sql ='insert into tb_maintable(anytext) values ('test')'
2017-09-18 01:24:46,059:DEBUG:Error reading record with key None , exception message (207, "Invalid column name 'None'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n"), sql = 'select pk_id,anytext from tb_maintable where pk_id = None'
2017-09-18 15:48:51,853:DEBUG:Error adding record , exception message 'DAOBase' object has no attribute 'get_add_record_query' , sql ='None'
2017-09-18 15:49:01,084:DEBUG:Error adding record , exception message 'DAOBase' object has no attribute 'get_add_record_query' , sql ='None'
2017-09-18 15:50:18,289:DEBUG:Error adding record , exception message 'DAOBase' object has no attribute 'get_add_record_query' , sql ='None'
2017-09-18 15:51:13,202:DEBUG:Error reading record with key 801 , exception message (u'HY090', u'[HY090] [unixODBC][Driver Manager]Invalid string or buffer length'), sql = ''
2017-09-18 15:55:46,387:DEBUG:Error reading record with key 803 , exception message Statement not executed or executed statement has no resultset, sql = ''
2017-09-18 16:02:00,659:DEBUG:Error reading record with key 805 , exception message Statement not executed or executed statement has no resultset, sql = ''
2017-09-18 16:15:37,553:DEBUG:Error reading record with key 811 , exception message (u'HY090', u'[HY090] [unixODBC][Driver Manager]Invalid string or buffer length'), sql = ''
2017-09-18 16:16:15,222:DEBUG:Error reading record with key 813 , exception message (u'HY090', u'[HY090] [unixODBC][Driver Manager]Invalid string or buffer length'), sql = ''
2017-09-18 16:16:44,443:DEBUG:Error reading record with key 815 , exception message (u'HY090', u'[HY090] [unixODBC][Driver Manager]Invalid string or buffer length'), sql = ''
2017-09-19 04:55:26,980:DEBUG:Error adding record , exception message object of type 'NoneType' has no len() , sql ='None'
2017-09-19 04:59:52,552:DEBUG:Error reading record with key 817 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'None'
2017-09-19 05:19:07,623:DEBUG:Error adding record , exception message 'DAODelegateTest' object has no attribute '_DAODelegate__addDef' , sql ='None'
2017-09-19 05:19:36,499:DEBUG:Error adding record , exception message 'DAODelegateTest' object has no attribute '_DAODelegate__addDef' , sql ='None'
2017-09-19 05:23:57,163:DEBUG:Error adding record , exception message 'DAODelegateTest' object has no attribute '_DAODelegate__addDef' , sql ='None'
2017-09-19 05:27:46,180:DEBUG:Error reading record with key 819 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'None'
2017-09-19 05:29:27,208:DEBUG:Error reading record with key 821 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'None'
2017-09-19 05:29:32,525:DEBUG:Error reading record with key 823 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'None'
2017-09-19 05:29:48,469:DEBUG:Error reading record with key 825 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'None'
2017-09-19 05:31:06,926:DEBUG:Error reading record with key 827 , exception message (u'42S22', u"[42S22] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'None'."), sql = 'None'
2017-09-19 05:34:03,206:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 05:34:11,206:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:05:37,968:DEBUG:Error adding record , foreign key error,sql = 'None'
2017-09-19 15:05:44,170:DEBUG:Error adding record , foreign key error,sql = 'None'
2017-09-19 15:05:54,008:DEBUG:Error adding record , foreign key error,sql = 'None'
2017-09-19 15:07:21,162:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:07:26,211:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:07:31,065:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:11:03,387:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:11:59,628:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:12:05,185:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:13:21,678:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:13:46,754:DEBUG:Error adding record , exception message (u'23000', u"[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'IX_tb_maintable_fk'. Cannot insert duplicate key in object 'dbo.tb_maintable_fk'. The duplicate key value is (IsDuplicate10).") , sql ='None'
2017-09-19 15:13:55,789:DEBUG:Error adding record , exception message (u'23000', u"[23000] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Violation of UNIQUE KEY constraint 'IX_tb_maintable_fk'. Cannot insert duplicate key in object 'dbo.tb_maintable_fk'. The duplicate key value is (IsDuplicate10).") , sql ='None'
2017-09-19 15:15:53,212:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:16:07,913:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 15:16:19,143:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:29:44,774:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:29:55,554:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:30:03,454:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:31:13,347:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:33:08,541:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:34:20,422:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:45:27,097:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:45:48,475:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 16:47:11,182:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-19 17:08:19,583:DEBUG:Error adding record , foreign key error,sql = 'None'
2017-09-19 17:08:34,430:DEBUG:Error adding record , foreign key error,sql = 'None'
2017-09-20 02:28:15,833:DEBUG:Error adding record , exception message tuple index out of range , sql ='None'
2017-09-20 02:29:15,562:DEBUG:Error adding record , exception message tuple index out of range , sql ='None'
2017-09-20 02:29:43,583:DEBUG:Error adding record , exception message tuple index out of range , sql ='None'
2017-09-20 02:31:12,860:DEBUG:Error adding record , exception message tuple index out of range , sql ='None'
2017-09-20 02:31:46,256:DEBUG:Error adding record , exception message (207, "Invalid column name 'main_code'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n") , sql ='None'
2017-09-20 05:09:44,650:DEBUG:Too many records 2 results for read a record with query - None
2017-09-20 05:13:14,518:DEBUG:Too many records 2 results for read a record with query - None
2017-09-20 05:14:54,198:DEBUG:Too many records 2 results for read a record with query - None
2017-09-20 05:17:29,691:DEBUG:Error adding record , exception message (2601, "Cannot insert duplicate key row in object 'dbo.tb_maintable_ckeys' with unique index 'IX_tb_maintable_ckeys'. The duplicate key value is (001, 1).DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\n") , sql ='None'
2017-09-20 05:21:00,606:DEBUG:Error adding record , exception message (2601, "Cannot insert duplicate key row in object 'dbo.tb_maintable_ckeys' with unique index 'IX_tb_maintable_ckeys'. The duplicate key value is (001, 1).DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\n") , sql ='None'
2017-09-20 05:21:05,116:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-20 05:21:35,514:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-20 05:21:46,062:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-20 05:22:12,885:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-21 01:44:33,095:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'None'
2017-09-21 02:20:21,470:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 02:21:40,471:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 04:11:26,358:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 04:24:18,683:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 04:33:11,418:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 04:34:19,694:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 04:39:30,423:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 15:43:21,436:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 15:45:22,561:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 15:47:42,201:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('002',1,'Soy 0002')'
2017-09-21 16:08:02,421:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('003',3,'Soy 0003')'
2017-09-21 16:34:30,563:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('003',3,'Soy 0003')'
2017-09-23 15:59:53,910:DEBUG:Error adding record , exception message 'DAODelegateTest' object has no attribute '_DatabaseDAODelegate__add_def' , sql ='insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('004',4,'Soy 0004')'
2017-09-23 16:01:01,572:DEBUG:Error adding record , exception message 'DAODelegateTest' object has no attribute '_DatabaseDAODelegate__add_def' , sql ='insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('004',4,'Soy 0004')'
2017-09-23 16:01:37,690:DEBUG:Error adding record , exception message 'DAODelegateTest' object has no attribute '_DatabaseDAODelegate__add_def' , sql ='insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('004',4,'Soy 0004')'
2017-09-23 19:52:45,790:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('004',4,'Soy 0004')'
2017-09-24 05:03:28,677:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('004',4,'Soy 0004')'
2017-09-24 05:42:54,842:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_maintable_ckeys(main_code,main_number,anytext) values ('005',5,'Soy 0005')'
