2017-08-29 00:26:18,767:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:26:18,789:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='execute uspaddFactura4 339,'2018-01-01','car339''
2017-08-29 00:26:58,311:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:27:33,441:DEBUG:Error adding record , exception message 'NoneType' object has no attribute '__getitem__' , sql ='execute uspaddFactura4 339,'2018-01-01','car339''
2017-08-29 00:27:40,760:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:27:40,785:DEBUG:Error adding record , exception message local variable 'unique_id' referenced before assignment , sql ='execute uspaddFactura4 339,'2018-01-01','car339''
2017-08-29 00:28:21,151:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:30:21,846:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:30:21,872:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'execute uspaddFactura4 339,'2018-01-01','car339';select SCOPE_IDENTITY()'
2017-08-29 00:30:34,148:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:35:23,946:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:35:40,441:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'execute uspaddFactura4 340,'2018-01-01','car340';select SCOPE_IDENTITY()'
2017-08-29 00:35:56,639:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:36:18,732:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 00:59:29,620:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:02:30,546:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:02:46,976:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:12:03,029:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:37:01,849:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:37:01,870:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:38:54,610:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:38:54,633:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:39:45,863:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:39:45,883:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:40:14,494:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:41:27,749:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:44:40,927:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:45:12,664:DEBUG:Error adding record , exception message (8114, 'Error converting data type varchar to int.DB-Lib error message 8114, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:49:47,134:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:50:07,444:DEBUG:Error adding record , exception message 'datetime.date' object has no attribute 'factura_fecha' , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:50:37,080:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 01:50:50,674:DEBUG:Error adding record , exception message (8114, 'Error converting data type varchar to int.DB-Lib error message 8114, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 01:59:44,246:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:00:07,904:DEBUG:Error adding record , exception message (8114, 'Error converting data type varchar to int.DB-Lib error message 8114, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 02:23:15,097:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:23:15,115:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 350,'2018-01-01','car350''
2017-08-29 02:25:20,742:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:26:05,225:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 02:28:16,167:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:28:16,182:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 02:29:27,539:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 02:29:27,555:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 04:07:47,121:DEBUG:Error adding record , exception message 'MySQLTestModel' object has no attribute 'factura_id' , sql ='insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:07:47,140:DEBUG:Error adding record , exception message Statement not executed or executed statement has no resultset , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 04:09:40,438:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:09:40,458:DEBUG:Error adding record , exception message (8144, 'Procedure or function uspaddFactura4 has too many arguments specified.DB-Lib error message 8144, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n') , sql ='execute uspaddFactura4 360,'2018-01-01','car360''
2017-08-29 04:10:21,719:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:13:35,569:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:15:16,014:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 04:15:23,505:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'execute uspaddFactura4 361,'car361''
2017-08-29 04:15:44,639:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 05:02:42,252:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-08-29 05:02:42,273:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'EXEC uspaddFactura4 362,'car362''
2017-08-29 05:02:56,812:DEBUG:Error adding record , ya existe un registro con la misma llave,sql = 'insert into tb_atletas(id_atletas,tb_atletas_nombres,id_referenced) values (117,'Soy usuario de test 117',1)'
2017-09-09 16:39:12,771:DEBUG:Error adding record , exception message 'MainTableModel' object has no attribute 'factura_id' , sql ='None'
